### ISSUE TITLE
Error when running codecept tests

### ISSUE THREAD

**Issue by antoineverger** [andrezap/crawler#1]
When I run the command you wrote : `vendor/bin/codecept run --steps` from the root folder, I get the following error message : 

> In Finder.php line 539:
>   The "/Users/antoineverger/Documents/Code/crawler/tests/acceptance/" directory does not exist.

**Comment by andrezap** [comment]
Sorry, didn't realize that wouldnt work without the folder, I assumed that codeception would create it empty
